### PR TITLE
[DO NOT MERGE] Show late cancellations in utilisation report

### PR DESCRIPTION
**Pull request by AndrewVos**
Late cancellations are appointments that got cancelled with less than
two working days until the appointment starts.

### CODE REVIEW

**Comment by benlovell** [comment]
We can hold off on this for a while. Need to think about the efficiency of this report.

**Comment by AndrewVos** [comment]
@benlovell I can remove the `[do-not-merge]` now yeah?

**Comment by benlovell** [comment]
@AndrewVos Not yet. This report was already hosing the server, these changes make it even worse and we need to think of a smarter / more efficient approach to reporting generally.

I think maybe in the short term, a smarter apprach would be to start flagging appointments as 'late cancellations' in the background on a schedule, or in the foreground at the time they're cancelled. It seems like a concern that should be first-class to me anyway, regardless of the reporting needs.

At least this way we wouldn't be digging back into the audits, we're doing this more and more in several places and to be honest we misuse them a little.

**Comment by AndrewVos** [comment]
Cool, I think I'll save CSV to `/tmp/blah` like this then: http://stackoverflow.com/questions/1517635/save-pl-pgsql-output-from-postgresql-to-a-csv-file#1517692

It should drop the memory usage massively.

**Comment by AndrewVos** [comment]
:cry:

**Pull request closed without merging**
