### PR TITLE
Add missing compound index on start / end at

### PR DESCRIPTION
**Pull request by benlovell**
We commonly query these fields together thus they benefit from a
compound index.

### CODE REVIEW

**Comment by dwhenry** [comment]
Can we see in the explain plans, query run times that this improves performance? 😄

**Comment by AndrewVos** [comment]
I've been wanting to add `spec/benchmarks` for a while :)

**Comment by dwhenry** [comment]
Or get freaky and try something like: https://www.postgresql.org/docs/9.6/static/rangetypes.html

**Comment by benlovell** [comment]
I've been playing with this locally and it seems adding a single index on `end_at` yields better results, which is absolutely unexpected. I'm going to close this for now while I figure this out. 👋

**Pull request closed without merging**
