### PR TITLE
Altered way jquery finds DOM elements across different modules

### PR DESCRIPTION
**Pull request by Guntrisoft**
- GOVUK Admin standard is to use classes with .js- prefix
https://github.com/alphagov/govuk_admin_template/blob/master/JAVASCRIPT.md
- altered any finding of DOM elements with $('[data-X]') to
  $('.js-X') to be consistent

### CODE REVIEW

**Comment by AndrewVos** [comment]
Truly a noble cause.

**Comment by benbarnett** [comment]
Please can you try and limit the force pushing after you've sent up for review? Makes it tricky to know what's changed

**Comment by AndrewVos** [comment]
If you're sure this works then merge away :)

**Comment by Guntrisoft** [comment]
I'm gonna do a manual run through of the things it affects and if all good i'll merge it!

**Comment by benbarnett** [comment]
It needs a rebase to see the holiday stuff but seems like most things are working!

**Pull request merged**
