### PR TITLE
Use server clock to set current date

### PR DESCRIPTION
**Pull request by benlovell**
This allows us to time travel successfully in our feature specs and ends
a whole class of spec bugs caused by @AndrewVos' incompetence.

### CODE REVIEW

**Comment by Guntrisoft** [comment]
😆👍 💯

**Comment by AndrewVos** [comment]
Looks good, aside from obvious factual inaccuracies in the description (I am in fact a genius).

Might be better to just inject some javascript mocking the date when using `travel_to` though. This feels like a test concern bleeding into code.

**Comment by benlovell** [comment]
@AndrewVos Maybe. But I can see the argument for both sides. Setting the default time / date using data attributes is certainly more straight-forward and it feels a bit scuzzy to be using mocks (javascript or otherwise) in feature specs.

**Comment by AndrewVos** [comment]
Hm, I agree.

**Pull request merged**
