### PR TITLE
Allow guiders to edit their own appointments

### PR DESCRIPTION
**Pull request by benlovell**
The guider can modify the personal details stored against appointments
assigned to them.

I extracted the common fields from new / edit into a partial to be
reused across both actions.

### CODE REVIEW

**Comment by AndrewVos** [comment]
How do they get to this page?

**Comment by benlovell** [comment]
@AndrewVos from clicking an appointment on their calendar. There is a spec for that side of the behaviour over here: https://github.com/guidance-guarantee-programme/telephone_appointment_planner/blob/5ac65f702b1d6ccf15f4c81e13c64ae127a4339c/spec/features/guider_views_appointments_spec.rb#L13

**Comment by Guntrisoft** [comment]
Looks good from my point of view 💯

**Comment by AndrewVos** [comment]
This is the best pull request I have ever seen in my life. Please merge it.

**Pull request merged**
